#!/usr/bin/env python3
"""Write cases/index.json and coord/index.json.

Static hosting cannot list a directory, so the two pickers are fed from
committed listings. Regenerated by the Pages workflow, so they cannot go stale.
"""
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

cases = []
for p in sorted(glob.glob(os.path.join(ROOT, 'cases', '*.json'))):
    name = os.path.basename(p)[:-5]
    if name == 'index':
        continue
    d = json.load(open(p))
    cases.append({'name': name, 'file': name + '.json',
                  'buses': len(d['p']), 'edges': len(d['edges']),
                  'display': 'display' in d})
with open(os.path.join(ROOT, 'cases', 'index.json'), 'w') as f:
    json.dump({'cases': cases}, f, indent=1)

coords = sorted(os.path.basename(p)[:-4]
                for p in glob.glob(os.path.join(ROOT, 'coord', '*.csv')))
with open(os.path.join(ROOT, 'coord', 'index.json'), 'w') as f:
    json.dump({'files': coords}, f, indent=1)

print('cases/index.json : %s' % ', '.join(c['name'] for c in cases))
print('coord/index.json : %s' % ', '.join(coords))
